server:
  port: 8081

spring:
  output:
    ansi:
      enabled: always
  datasource:
    url: jdbc:mysql://localhost:3306/warehouse_db?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql

rocketmq:
  name-server: localhost:9876
  consumer:
    group: warehouse-consumer-group

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    com.baomidou.mybatisplus: WARN
    org.apache.ibatis: WARN
